server:
  port: 6277
  host: "0.0.0.0"
  mode: "release" # "release" or "debug"

database:
  type: "sqlite"
  path: "data/ech0.db"
  logmode: "release" # "release" or "debug"

auth:
  jwt:
    expires: 2592000 # 30天（单位秒）
    issuer: "ech0"
    audience: "ech0"

upload:
  imagemaxsize: 20971520 #  20MB
  audiomaxsize: 20971520 # 20MB
  videomaxsize: 104857600 # 100MB
  imagepath: "data/images/"
  audiopath: "data/audios/"
  videopath: "data/videos/"
  allowedtypes:
    - "image/jpeg"
    - "image/png"
    - "image/gif"
    - "image/webp"
    - "image/jpg"
    - "image/svg+xml"
    - "image/avif"
    - "image/heic"
    - "image/heif"
    - "image/heic-sequence"
    - "audio/mpeg"
    - "audio/flac"
    - "audio/wav"
    - "audio/mp4"
    - "video/mp4"
    - "video/webm"
    - "video/quicktime"

setting:
  sitetitle: "Ech0"
  serverlogo: "/Ech0.svg"
  servername: "Ech0"
  serverurl: "https://ech0.example.com"
  allowregister: true
  icpnumber: ""
  metingapi: ""
  customcss: ""
  customjs: ""

comment:
  enablecomment: false
  provider: "twikoo"
  commentapi: ""

ssh:
  port: "6278"
  host: "0.0.0.0"
  key: "data/ssh/id_ed25519"
