name: Build and Push Docker Image

on:
  push:
    branches:
    - 'custom'
  workflow_dispatch:

jobs:
  build-docker:
    name: Build and Push Docker Image (linux/amd64)
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ”„ Checkout source code
        uses: actions/checkout@v4

      - name: ğŸ³ Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: ğŸ“¦ Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: ğŸ³ Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/ech0:${{ github.sha }}
            ${{ vars.DOCKERHUB_USERNAME }}/ech0:latest